# Generated by Django 3.0.3 on 2021-03-16 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('cars', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.Cars')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.Models')),
            ],
        ),
    ]
