# Generated by Django 3.0.3 on 2021-03-16 11:10

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Academie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academie', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BacMention',
            fields=[
                ('mention', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('code', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='DiplomeBacPlus2',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=120)),
                ('nature', models.CharField(blank=True, max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='EtablissementDipBacPlus2',
            fields=[
                ('code', models.AutoField(db_column='BID', primary_key=True, serialize=False)),
                ('etablissement', models.CharField(max_length=180)),
            ],
        ),
        migrations.CreateModel(
            name='ResponsableLPs',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nom', models.CharField(default='', max_length=60)),
                ('prenom', models.CharField(default='', max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
            ],
        ),
        migrations.CreateModel(
            name='Specialite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialite', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('cin_passeport', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TypeBac',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=60, unique=True)),
                ('autre', models.CharField(blank=True, default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('ville', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('etablissement', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='pages.EtablissementDipBacPlus2')),
            ],
        ),
        migrations.CreateModel(
            name='Lycee',
            fields=[
                ('code', models.AutoField(db_column='BID', primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('academie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Academie')),
            ],
        ),
        migrations.CreateModel(
            name='LPs',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nom', models.CharField(default='', max_length=120)),
                ('bac', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='pages.TypeBac')),
                ('codeDept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Departement')),
                ('codeResponsableDept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.ResponsableLPs')),
                ('diplome', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='pages.DiplomeBacPlus2')),
            ],
        ),
        migrations.CreateModel(
            name='Candidat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cin_passeport', models.CharField(max_length=10, unique=True)),
                ('cne_massar', models.CharField(max_length=10)),
                ('nom', models.CharField(max_length=20)),
                ('prenom', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=20)),
                ('dateNaissance', models.DateField()),
                ('nationalite', django_countries.fields.CountryField(max_length=2)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone1', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('telephone2', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('addresse', models.CharField(blank=True, max_length=200)),
                ('ville', models.CharField(choices=[('Agadir', 'Agadir'), ('Beni Mellal', 'Beni Mellal'), ('Casablanca', 'Casablanca'), ('Dakhla', 'Dakhla'), ('El Jadida', 'El Jadida'), ('Fes', 'Fes'), ('Kenitra', 'Kenitra'), ('Khenifra', 'Khenifra'), ('Laayoune', 'Laayoune'), ('Larache', 'Larache'), ('Marrakech', 'Marrakech'), ('Martil', 'Martil'), ('Meknes', 'Meknes'), ('Mohammedia', 'Mohammedia'), ('Oujda', 'Oujda'), ('Rabat', 'Rabat'), ('Sale', 'Sale'), ('Tanger', 'Tanger'), ('Tetouan', 'Tetouan'), ('Dakhla', 'Dakhla'), ('Laayoune', 'Laayoune'), ('Guelmim', 'Guelmim'), ('Tafilalet', 'Tafilalet'), ('Souss', 'Souss')], max_length=60)),
                ('annee_obtenetion_bac', models.CharField(choices=[('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020')], default='2018', max_length=5)),
                ('anneeObtentionDiplomeBacPlus2', models.CharField(choices=[('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020')], default='2020', max_length=4)),
                ('anneeObtention1ereAnnee', models.CharField(choices=[('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020')], default='2019', max_length=4)),
                ('dominanceDiplome', models.CharField(blank=True, max_length=60, null=True)),
                ('dureeObtentionDiplome', models.CharField(max_length=1)),
                ('note1ereAnneeDiplome', models.CharField(blank=True, max_length=6)),
                ('note2ereAnneeDiplome', models.CharField(blank=True, max_length=6)),
                ('noteObtentionDiplome', models.CharField(blank=True, max_length=6)),
                ('noteSemestre1', models.CharField(blank=True, max_length=6)),
                ('noteSemestre2', models.CharField(blank=True, max_length=6)),
                ('noteSemestre3', models.CharField(blank=True, max_length=6)),
                ('noteSemestre4', models.CharField(blank=True, max_length=6)),
                ('academie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Academie')),
                ('codeBac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.TypeBac')),
                ('codeLPChoisie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.LPs')),
                ('diplomeBacPlus2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.DiplomeBacPlus2')),
                ('etablissementDiplomeBacPlus2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.EtablissementDipBacPlus2')),
                ('lycee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Lycee')),
                ('mentionBac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.BacMention')),
                ('specialiteDiplome', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='pages.Specialite')),
                ('villeDiplomeBacPlus2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Ville')),
            ],
        ),
        migrations.AddField(
            model_name='academie',
            name='ville',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Ville'),
        ),
        migrations.CreateModel(
            name='LPsDiplomeBacPlus2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeDiplomeBacPlus2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.DiplomeBacPlus2')),
                ('codeLP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.LPs')),
            ],
            options={
                'unique_together': {('codeLP', 'codeDiplomeBacPlus2')},
            },
        ),
        migrations.CreateModel(
            name='LPsBac',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeBac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.TypeBac')),
                ('codeLP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.LPs')),
            ],
            options={
                'unique_together': {('codeLP', 'codeBac')},
            },
        ),
    ]
