# Generated by Django 3.0.3 on 2021-03-12 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidat',
            name='documentJustificatif',
        ),
    ]
