# Generated by Django 3.0.3 on 2021-03-16 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20210316_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lps',
            name='bac',
        ),
        migrations.RemoveField(
            model_name='lps',
            name='diplome',
        ),
        migrations.AddField(
            model_name='diplomebacplus2',
            name='lp',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='pages.LPs'),
        ),
        migrations.AddField(
            model_name='typebac',
            name='lp',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='pages.LPs'),
        ),
    ]
