# Generated by Django 3.0.3 on 2021-03-13 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_remove_candidat_documentjustificatif'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidat',
            old_name='DiplomeBacPlus2',
            new_name='diplomeBacPlus2',
        ),
    ]
