# Generated by Django 3.0.3 on 2021-03-13 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_candidat_dureeobtentiondiplome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidat',
            name='anneeObtention1ereAnnee',
            field=models.CharField(max_length=4),
        ),
    ]
